### ISSUE TITLE
Webpack 2.2.0-rc.4 throws an error because karma-webpack passes incorrect entry option

### ISSUE THREAD

**Issue by Reinmar** [webpack/karma-webpack#193] opened 2017-01-11 16:53 UTC
**I'm submitting a bug report**

**Webpack version:**

2.2.0-rc.4

**Webpack Karma version**:

1.8.1

**Karma version**:

1.3.0

**Please tell us about your environment:**

OSX 10.12

**Current behavior:**

```
11 01 2017 17:47:50.284:ERROR [preprocess]: Can not load "webpack"!
  WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.entry should be one of these:
   object { <key>: non-empty string | [non-empty string] } | non-empty string | [non-empty string] | function
   The entry point(s) of the compilation.
   Details:
    * configuration.entry should NOT have less than 1 properties ({
        "keyword": "minProperties",
        "dataPath": ".entry",
        "schemaPath": "#/oneOf/0/minProperties",
        "params": {
          "limit": 1
        },
        "message": "should NOT have less than 1 properties",
        "schema": 1,
        "parentSchema": {
          "minProperties": 1,
          "additionalProperties": {
            "oneOf": [
              {
                "description": "The string is resolved to a module which is loaded upon startup.",
                "minLength": 1,
                "type": "string"
              },
              {
                "description": "All modules are loaded upon startup. The last one is exported.",
                "$ref": "#/definitions/common.nonEmptyArrayOfUniqueStringValues"
              }
            ]
          },
          "description": "Multiple entry bundles are created. The key is the chunk name. The value can be a string or an array.",
          "type": "object"
        },
        "data": {}
      }).
      object { <key>: non-empty string | [non-empty string] }
      Multiple entry bundles are created. The key is the chunk name. The value can be a string or an array.
    * configuration.entry should be a string.
    * configuration.entry should be an array:
      [non-empty string]
    * configuration.entry should be an instance of function
      function returning an entry object or a promise..
    at webpack (/www/ckeditor5/ckeditor5-dev/packages/ckeditor5-dev-tests/node_modules/webpack/lib/webpack.js:20:9)
    at new Plugin (/www/ckeditor5/ckeditor5-dev/packages/ckeditor5-dev-tests/node_modules/karma-webpack/lib/karma-webpack.js:63:18)
    at invoke (/www/ckeditor5/ckeditor5-dev/packages/ckeditor5-dev-tests/node_modules/di/lib/injector.js:75:15)
    at Array.instantiate (/www/ckeditor5/ckeditor5-dev/packages/ckeditor5-dev-tests/node_modules/di/lib/injector.js:59:20)
    at get (/www/ckeditor5/ckeditor5-dev/packages/ckeditor5-dev-tests/node_modules/di/lib/injector.js:48:43)
    at /www/ckeditor5/ckeditor5-dev/packages/ckeditor5-dev-tests/node_modules/di/lib/injector.js:71:14
    at Array.map (native)
    at Array.invoke (/www/ckeditor5/ckeditor5-dev/packages/ckeditor5-dev-tests/node_modules/di/lib/injector.js:70:31)
    at Injector.get (/www/ckeditor5/ckeditor5-dev/packages/ckeditor5-dev-tests/node_modules/di/lib/injector.js:48:43)
    at instantiatePreprocessor (/www/ckeditor5/ckeditor5-dev/packages/ckeditor5-dev-tests/node_modules/karma/lib/preprocessor.js:55:20)
    at Array.forEach (native)
```

**Expected/desired behavior:**

It worked fine with Webpack 2.2.0-rc.3. Webpack either hasn't been validating the `entry` option or the validation was more loose.

The config which karma-webpack passes to Webpack is this:

```
{ plugins: [ CKEditorWebpackPlugin { options: [Object] } ],
  module: { rules: [ [Object], [Object] ] },
  resolveLoader:
   { modules:
      [ 'node_modules',
        '/www/ckeditor5/ckeditor5-dev/packages/ckeditor5-dev-tests/node_modules' ] },
  watch: true,
  entry: {},
  output:
   { path: '/_karma_webpack_/',
     publicPath: '/_karma_webpack_/',
     filename: '[name]',
     chunkFilename: '[id].bundle.js' } }
```

The important part is `entry: {}`.

**Comment by egoroof** [comment] 2017-01-11 16:57
I was first 😄

**Comment by Reinmar** [comment] 2017-01-11 16:58
You mean https://github.com/webpack/karma-webpack/issues/192? Perhaps it's the same issue, but there are no details what went wrong in your ticket.

**Comment by Reinmar** [comment] 2017-01-11 16:59
Not sure if this is relevant, but here's the config which we pass to Karma:

```
{ basePath: '/www/ckeditor5/ckeditor5',
  frameworks: [ 'mocha', 'chai', 'sinon' ],
  files: [ '/www/ckeditor5/ckeditor5/node_modules/ckeditor5-autoformat/tests/**/*.js' ],
  exclude: [ '**/tests/**/_utils/**/*.js', '**/tests/**/manual/**/*.js' ],
  preprocessors: { '/www/ckeditor5/ckeditor5/node_modules/ckeditor5-autoformat/tests/**/*.js': [ 'webpack' ] },
  webpack:
   { plugins:
      [ CKEditorWebpackPlugin {
          options:
           { packages:
              [ '/www/ckeditor5/ckeditor5',
                '/www/ckeditor5/ckeditor5/node_modules' ] } } ],
     module:
      { rules:
         [ { test: /ckeditor5-[^\/]+\/theme\/icons\/[^\/]+\.svg$/,
             use: [ 'raw-loader' ] },
           { test: /\.scss$/,
             use: [ 'style-loader', 'css-loader', 'sass-loader' ] } ] },
     resolveLoader:
      { modules:
         [ 'node_modules',
           '/www/ckeditor5/ckeditor5-dev/packages/ckeditor5-dev-tests/node_modules' ] } },
  webpackMiddleware: { noInfo: true, stats: { chunks: false } },
  reporters: [ 'mocha' ],
  port: 9876,
  colors: true,
  logLevel: 'INFO',
  browsers: [ 'Chrome' ],
  customLaunchers: { CHROME_TRAVIS_CI: { base: 'Chrome', flags: [ '--no-sandbox' ] } },
  singleRun: true,
  concurrency: Infinity,
  browserNoActivityTimeout: 0 }
```

**Comment by TheLarkInn** [comment] 2017-01-11 17:23
What if you pass `entry: []`? We did add more constraints on the entry property validation.

**Comment by Reinmar** [comment] 2017-01-11 17:26
I added `options.entry = [];` in webpack.js:

```js
function webpack(options, callback) {
	options.entry = [];
```

And I got the same error.

**Comment by Reinmar** [comment] 2017-01-11 17:29
A quick workaround can be to set `options.entry` to `'whatever'` and besides:

```
ERROR in Entry module not found: Error: Can't resolve 'whatever' in '/www/ckeditor5/ckeditor5'
```

The tests run and pass :)

**Comment by TheLarkInn** [comment] 2017-01-11 17:54
Could you make a tiny example of this for me to reproduce and add to test cases.

**Comment by gyandeeps** [comment] 2017-01-11 18:49
Quick work around was 

```js
webpackOptions.entry = function(){return {}};
```

this way it works like it used to. I dont know if this a good long term solution.

**Comment by TheLarkInn** [comment] 2017-01-11 18:51
No this is exactly how we will fix it. thank you

**Comment by gyandeeps** [comment] 2017-01-11 18:52
Will send a PR. Thanks @TheLarkInn

**Comment by d3viant0ne** [comment] 2017-01-11 19:03
@gyandeeps - Be mindful to open said pull request to https://github.com/webpack/karma-webpack/tree/v1 & not master. I'll land it as soon as it arrives.

**Comment by gyandeeps** [comment] 2017-01-11 19:04
@d3viant0ne It took me a while to figure out why the index.js was empty. lol
here is the PR: https://github.com/webpack/karma-webpack/pull/194

**Comment by d3viant0ne** [comment] 2017-01-11 19:05
Already merged. @TheLarkInn will cut a patch release shortly

**Comment by gyandeeps** [comment] 2017-01-11 19:12
@d3viant0ne Please merge this PR https://github.com/webpack/karma-webpack/pull/195 as I had some lint issues in previous one.

**Comment by d3viant0ne** [comment] 2017-01-11 19:12
Already done. I'm quick with that little green button of doom :)

**Comment by TheLarkInn** [comment] 2017-01-11 19:15
Before I publish, since I can't test this via our current suite, would someone mind running this commit against their build to ensure it works. I don't have a local reproducible example of this. // @Reinmar @egoroof

**Comment by gyandeeps** [comment] 2017-01-11 19:17
@TheLarkInn I actually tested it with my karma webpack (rc4) setup. That how I figured this out.
I have not tested it with old webpack.

**Comment by d3viant0ne** [comment] 2017-01-11 19:21
@TheLarkInn - Verifying it now

**Comment by TheLarkInn** [comment] 2017-01-11 19:24
Awesome thank you. Also @MikaAK You are the only one with privileges can you publish this?

**Comment by TheLarkInn** [comment] 2017-01-11 19:24
I have the tags pushed and release commits pushed.

**Comment by d3viant0ne** [comment] 2017-01-11 19:24
Besides the usual suspects, i.e. @sokra

**Comment by gyandeeps** [comment] 2017-01-11 19:50
@TheLarkInn I saw u created a release but i am not seeing it here anymore: https://github.com/webpack/karma-webpack/releases

Even its not their on npm.

**Comment by d3viant0ne** [comment] 2017-01-11 19:50
I removed the tag as it still throws the same error

**Comment by gyandeeps** [comment] 2017-01-11 19:51
huh... it worked for me with webpack (rc4). Can you share your setup or any details.

**Comment by d3viant0ne** [comment] 2017-01-11 19:58
Note to absolutely everyone who will run into this. Most common webpack test configurations set `entry: {}` to include all of mine.

When updating to `"webpack": "2.2.0-rc.4"` & `"karma-webpack": "1.8.2"` you have to pull the `entry` property if it's set to an empty object so it defaults to a function within karma-webpack and you don't beat your head against the desk and look like a total ass in a github issue like me :)

**Comment by gyandeeps** [comment] 2017-01-11 20:00
ah i see. Should we just check if its an empty object (`Object.keys(webpackOptions.entry).length === 0`) then just replace it with function as well ?

**Comment by d3viant0ne** [comment] 2017-01-11 20:01
I'll stick a note in the tag regarding the required change.

**Comment by gyandeeps** [comment] 2017-01-11 20:04
I would recommend `0.9.0` tag release, so that people know that thr are some breaking changes.

**Comment by d3viant0ne** [comment] 2017-01-11 20:06
It's a fix for a breaking change in Webpack ( technically ) not something I would cut a major for.

When using anything but rc.4 it behaves exactly as it did before as it's just failing on schema validation in Webpack.

**Comment by gyandeeps** [comment] 2017-01-11 20:17
Sounds good. I will wait for npm to start showing me 1.8.2
Its been lil slow lately.

**Comment by gyandeeps** [comment] 2017-01-11 20:34
@TheLarkInn @d3viant0ne Has this been released to npm ?

**Comment by d3viant0ne** [comment] 2017-01-11 20:50
No, limited number or people with npm access. Taking care of that now.

**Comment by d3viant0ne** [comment] 2017-01-11 21:30
@gyandeeps - After a bit of discussion, the decision was made to make this a major after all.

Proper tag is cut here - https://github.com/webpack/karma-webpack/releases/tag/v2.0.0

@TheLarkInn should be pushing that up to npm shortly.

**Comment by d3viant0ne** [comment] 2017-01-11 21:39
Resolving - https://www.npmjs.com/package/karma-webpack @ `2.0.0`

**Closed by d3viant0ne** 2017-01-11 21:39 UTC
Labels: awaiting response, bug, bug: dependency

**Comment by siemiatj** [comment] 2017-01-13 14:01
For anyone who stumbles upon that. I've recently migrated to Webpack 2 but my karma config stayed the same. And now when I was trying to run my tests with webpack-karma 2.0.1 I was getting : 

```
13 01 2017 14:45:10.390:ERROR [preprocess]: Can not load "webpack"!
  Error
    at webpack (/Users/sasklacz/Work/crowdspring/cs3/web/node_modules/webpack/lib/webpack.js:19:9)
    at new Plugin (/Users/sasklacz/Work/crowdspring/cs3/web/node_modules/karma-webpack/lib/karma-webpack.js:67:18)
    at invoke (/Users/sasklacz/Work/crowdspring/cs3/web/node_modules/di/lib/injector.js:75:15)
    at Array.instantiate (/Users/sasklacz/Work/crowdspring/cs3/web/node_modules/di/lib/injector.js:59:20)
    at get (/Users/sasklacz/Work/crowdspring/cs3/web/node_modules/di/lib/injector.js:48:43)
    at /Users/sasklacz/Work/crowdspring/cs3/web/node_modules/di/lib/injector.js:71:14
    at Array.map (native)
    at Array.invoke (/Users/sasklacz/Work/crowdspring/cs3/web/node_modules/di/lib/injector.js:70:31)
    at Injector.get (/Users/sasklacz/Work/crowdspring/cs3/web/node_modules/di/lib/injector.js:48:43)
    at instantiatePreprocessor (/Users/sasklacz/Work/crowdspring/cs3/web/node_modules/karma/lib/preprocessor.js:56:20)
    at Array.forEach (native)
    at createPreprocessor (/Users/sasklacz/Work/crowdspring/cs3/web/node_modules/karma/lib/preprocessor.js:75:20)
    at Array.invoke (/Users/sasklacz/Work/crowdspring/cs3/web/node_modules/di/lib/injector.js:75:15)
    at get (/Users/sasklacz/Work/crowdspring/cs3/web/node_modules/di/lib/injector.js:48:43)
    at /Users/sasklacz/Work/crowdspring/cs3/web/node_modules/di/lib/injector.js:71:14
    at Array.map (native)
```

which tells nothing at all. After some `.console.log('foo')` debugging it turned out that it was caused by an error in my karma.webpack config, but the error itself never bubbled up so it was hard to debug :

`message: 'Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.\n - configuration.resolve.extensions[0] should not be empty.',
  `

So be sure that your webpack config is correct before anything else :)

**Comment by chrisrwilkes** [comment] 2018-01-23 16:30
I have the same issue, updated here:
https://github.com/webpack-contrib/karma-webpack/issues/227#issuecomment-359836020

**Comment by mantupani17** [comment] 2018-03-06 09:13
i am having the same problem with webpack , i cant understand how do i resolve

**Comment by mpavkovic** [comment] 2018-08-11 18:50
@mantupani17 Have you tried @gyandeeps solution? It worked for me. I've shortened it a bit by using arrow functions
```js
webpackConfig.entry = () => ({});
```
