### ISSUE TITLE
cannot load 'webpack'

### ISSUE THREAD

**Issue by jingzhou123** [webpack/karma-webpack#70] opened 2015-08-04 06:56 UTC
```
Errors:
Can not load "webpack"!
  TypeError: undefined is not a function
    at Plugin.notifyKarmaAboutChanges (/Users/jz/jsfiddles/template/node_modules/karma-webpack/index.js:108:15)
    at Plugin.<anonymous> (/Users/jz/jsfiddles/template/node_modules/karma-webpack/index.js:72:9)
    at Tapable.applyPlugins (/Users/jz/jsfiddles/template/node_modules/webpack/node_modules/tapable/lib/Tapable.js:26:37)
    at Watching._done (/Users/jz/jsfiddles/template/node_modules/webpack/lib/Compiler.js:78:17)
    at Watching.<anonymous> (/Users/jz/jsfiddles/template/node_modules/webpack/lib/Compiler.js:61:18)
    at Tapable.emitRecords (/Users/jz/jsfiddles/template/node_modules/webpack/lib/Compiler.js:281:37)
    at Watching.<anonymous> (/Users/jz/jsfiddles/template/node_modules/webpack/lib/Compiler.js:58:19)
    at /Users/jz/jsfiddles/template/node_modules/webpack/lib/Compiler.js:274:11
    at Tapable.applyPluginsAsync (/Users/jz/jsfiddles/template/node_modules/webpack/node_modules/tapable/lib/Tapable.js:60:69)
    at Tapable.afterEmit (/Users/jz/jsfiddles/template/node_modules/webpack/lib/Compiler.js:271:8)
```
here is my package.json file
```json
{
  "name": "components",
  "version": "0.0.1",
  "description": "components",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    
    
    
    
  },
  "devDependencies": {
    "babel-core": "^5.8.9",
    "babel-loader": "^5.3.2",
    "css-loader": "^0.15.6",
    "jasmine-core": "^2.3.4",
    "karma": "^0.12.37",
    "karma-chrome-launcher": "^0.2.0",
    "karma-jasmine": "^0.3.6",
    "karma-sourcemap-loader": "^0.3.5",
    "karma-webpack": "^1.6.0",
    "less": "^2.5.1",
    "less-loader": "^2.2.0",
    "lodash": "^3.10.0",
    "style-loader": "^0.12.3",
    "webpack": "^1.10.5"
  }
}

```
I change karma version to `~0.12.37` and karma-webpack to `~1.6.0`，it works;
But when karma-webpack is 1.7.0, it throw errors when I run `karma start karma.config.js`

**Comment by Dignifiedquire** [comment] 2015-08-04 09:47
Duplicate of #68 and see #63 for more details. You need to upgrade karma to `0.13` to fix the issue

**Comment by pojka** [comment] 2015-08-04 12:42
I'm seeing this issue with fixed versions of karma 0.13.4 and karma-webpack 1.7.0 

```
Can not load "webpack"!
  TypeError: undefined is not a function
    at Plugin.notifyKarmaAboutChanges (/Projects/utilass/node_modules/karma-webpack/index.js:108:15)
```

**Comment by Dignifiedquire** [comment] 2015-08-04 13:02
@pojka could you show me the output of `npm ls` please

**Comment by pojka** [comment] 2015-08-04 13:09
@Dignifiedquire sure - https://gist.github.com/pojka/49307fbb77d1c0ee18ed

Please let me know if I'm being dumb :)

**Comment by Dignifiedquire** [comment] 2015-08-04 13:18
@pojka looks like there is another bug in there :( thanks for the report

**Comment by kmaraz** [comment] 2015-08-11 11:03
I have the same problem, how can I temporarily solve this? Or I need to wait for fix? Thanks.

**Comment by pojka** [comment] 2015-08-11 11:05
@kmaraz using the following combination works for me for the moment:

`
    "karma": "0.12.37",
    "karma-webpack": "1.6.0",
`

**Comment by kmaraz** [comment] 2015-08-11 11:07
@pojka Thanks!
@Dignifiedquire If you need my logs, just tell me, please.

**Comment by AndrewRevinsky** [comment] 2015-08-12 00:20
Hello, isn't there a way NOT to use old versions? :+1:

**Comment by leoselig** [comment] 2015-08-13 10:24
+1
we are experiencing the same issues

**Comment by Dignifiedquire** [comment] 2015-08-13 10:28
Does someone have repo which fails with this error, using `karma@0.13.9` and `karma-webpack@1.7.0` that I could look at?

**Comment by ebordeau** [comment] 2015-08-18 19:08
I updated to karma@0.13.9 and karma-webpack@1.7.0 and it worked for me. Thanks!

**Comment by pojka** [comment] 2015-08-19 02:47
@Dignifiedquire not working for me with `karma@0.13.9` and `karma-webpack@1.7.0` either

I've stripped everything down to a very basic config and a hello world test, repo is here - https://github.com/pojka/debug-karma-webpack-70

If you change to `karma@0.12.37` and `karma-webpack@1.6.0` the test runs

**Comment by thomasklein** [comment] 2015-09-01 08:50
Hi! Downgrading to karma@0.12.37 and karma-webpack@1.6.0 triggers the following error for me:

```
WARN [preprocess]: Can not load "webpack"!
  Error: Invalid arguments: 'delay'
    at NodeWatchFileSystem.watch (/xxx/node_modules/webpack/lib/node/NodeWatchFileSystem.js:29:9)
    at Watching.watch (/xxx/node_modules/webpack/lib/Compiler.js:86:47)
    at Watching._done (/xxx/node_modules/webpack/lib/Compiler.js:82:8)
    at Watching.<anonymous> (/xxx/node_modules/webpack/lib/Compiler.js:60:18)
    at Tapable.emitRecords (/xxx/node_modules/webpack/lib/Compiler.js:279:37)
    at Watching.<anonymous> (/xxx/node_modules/webpack/lib/Compiler.js:57:19)
    at /xxx/node_modules/webpack/lib/Compiler.js:272:11
    at Tapable.applyPluginsAsync (/xxx/node_modules/webpack/node_modules/tapable/lib/Tapable.js:60:69)
    at Tapable.afterEmit (/xxx/node_modules/webpack/lib/Compiler.js:269:8)
    at Tapable.<anonymous> (/xxx/node_modules/webpack/lib/Compiler.js:264:14)
```

with the karma.config

````
module.exports = function(config) {
    config.set({

        // base path that will be used to resolve all patterns (eg. files, exclude)
        basePath: pathToSrcJS,

        // frameworks to use
        // available frameworks: https://npmjs.org/browse/keyword/karma-adapter
        frameworks: ['jasmine'],

        // list of files / patterns to load in the browser
        files: [
            // project specific SETUP necessary for tests
            'components_tests/setup.js',

            // include all test files
            'components_tests/test_index.js'
        ],
        // preprocess matching files before serving them to the browser
        // available preprocessors: https://npmjs.org/browse/keyword/karma-preprocessor
        preprocessors: {
            'components_tests/test_index.js': ['webpack', 'coverage'],
            'components_tests/setup.js': ['webpack']
        },

        // list of files to exclude
        exclude: [],

        // TODO refactor path and make them project agnostic
        webpack: webpackConfig,

        // test results reporter to use
        // possible values: 'dots', 'progress'
        // available reporters: https://npmjs.org/browse/keyword/karma-reporter
        reporters: ['progress', 'coverage'],

        // web server port
        port: 9876,

        // enable / disable colors in the output (reporters and logs)
        colors: true,

        // Output summary only to console
        // Webstorm/Intellij have an integrated coverage view
        coverageReporter: {
            reporters: [{
                type: 'text'
            }]
        },

        // level of logging
        // possible values: config.LOG_DISABLE || config.LOG_ERROR || config.LOG_WARN || config.LOG_INFO || config.LOG_DEBUG
        logLevel: config.LOG_INFO,

        // enable / disable watching file and executing tests whenever any file changes
        autoWatch: false,

        // start these browsers
        // available browser launchers: https://npmjs.org/browse/keyword/karma-launcher
        browsers: ['PhantomJS'],

        // Continuous Integration mode
        // if true, Karma captures browsers, runs the tests and exits
        singleRun: true,

        plugins: [
            require('karma-phantomjs-launcher'),
            require('karma-webpack'),
            require('karma-jasmine'),
            require('karma-coverage')
        ]
    });
};
```

**Comment by thomasklein** [comment] 2015-09-01 09:00
My problem was solved by upgrading to the latest version of webpack.

**Comment by claudiopro** [comment] 2015-09-08 09:24
Same issue here. I'm running  a clone of https://github.com/pheuter/essential-react with

```
karma@0.12.37
karma-webpack@1.7.0
webpack@1.12.1
```

Full output of `npm ls` [here](https://gist.github.com/claudiopro/d8a1e19544c073afbcbc)

**Comment by Dignifiedquire** [comment] 2015-09-08 09:28
@claudiopro you need to upgrade karma to `0.13`

**Comment by claudiopro** [comment] 2015-09-08 09:29
@Dignifiedquire thanks, `karma@0.13.9` did solve the issue!

**Comment by Dignifiedquire** [comment] 2015-09-08 10:16
@pojka @jingzhou123 I've just checked you repo and everything is working fine for me, I ran

```bash
$ npm install
$ node_modules/.bin/karma start karma.conf.js
```

Could you check that you are using `karma-cli` and not `karma` installed globally, and make sure the global version which you call with `karma` is actually up to date.

**Comment by pojka** [comment] 2015-10-20 15:34
@Dignifiedquire that was indeed the issue, thank you for your patience!

**Comment by Dignifiedquire** [comment] 2015-10-20 15:48
Closing this as all issues seem to have been resolved.

**Closed by Dignifiedquire** 2015-10-20 15:48 UTC

**Comment by joeheyming** [comment] 2016-06-29 23:07
wow, this whole time I wasn't using node_modules/.bin/karma and was instead using the global karma.

Just wanted to say this in case anyone else had the same issue.

**Comment by hankthewhale** [comment] 2016-07-19 21:38
@joeheyming Good call out. Didn't even think of that. Completely fixed my issues.

**Comment by sahilpurav** [comment] 2018-03-26 08:28
I've the same problem My version looks fine too:

karma-webpack@3.0.0
├─ karma@1.7.1
└─ webpack@3.8.1
